### ISSUE TITLE
Add the author name to the search query

### ISSUE THREAD

**Issue by arogl** [JonDerThan/annas-goodreads#12]
OR include ISBN.

That may be part of the settings page you are looking into.

I use the userscript version

**Comment by JonDerThan** [comment]
I've found it difficult to properly add the author to the search query because names are often abbreviated and may be spelled differently depending on the language (e.g. "Fyodor Dostoyevsky" (Goodreads, all languages) "Fyodor Dostoevsky" (Wikipedia, English), "Fjodor Michailowitsch Dostojewski" (Wikipedia, German)).

Concerning the ISBN: AFAIK a book can have many ISBNs, one for each edition. Including it would unnecessarily limit the search to only this specific edition. (Additionally this would also add a lot of complexity to the code.)

I've often found myself manually adding the authors name to the search too though. Sadly I can't figure out a way to include it reliably and I'm not sure whether it's a good idea to exclude books from the search just because the authors name is spelled differently. Adding this option to a settings page is a great idea, I am currently not planning to work on adding one in the first place though, sadly. I'll add it to the issue however.
